"""plan_most_table_will_use(announcement, problemm ...)

Revision ID: bed3c3bbd0b0
Revises: 627f3bcbfddb
Create Date: 2024-10-31 15:49:57.866170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed3c3bbd0b0'
down_revision = '627f3bcbfddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('announcementid', sa.Integer(), nullable=False),
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('announce_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courseid'], ['course.courseid'], ),
    sa.PrimaryKeyConstraint('announcementid')
    )
    op.create_table('homework',
    sa.Column('homeworkid', sa.Integer(), nullable=False),
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courseid'], ['course.courseid'], ),
    sa.PrimaryKeyConstraint('homeworkid')
    )
    op.create_table('problem',
    sa.Column('problemid', sa.Integer(), nullable=False),
    sa.Column('homeworkid', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['homeworkid'], ['homework.homeworkid'], ),
    sa.PrimaryKeyConstraint('problemid')
    )
    op.create_table('submission',
    sa.Column('submissionid', sa.Integer(), nullable=False),
    sa.Column('problemid', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Float(), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problemid'], ['problem.problemid'], ),
    sa.PrimaryKeyConstraint('submissionid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('problem')
    op.drop_table('homework')
    op.drop_table('announcement')
    # ### end Alembic commands ###
