FROM python:3.10
LABEL maintainer="matingwei929@gmail.com"

RUN apt-get update -y && \
    apt-get clean

COPY . /app

WORKDIR /app

RUN chown -R root:root /app && \
    pip install -r requirements.txt

USER root

CMD ["python", "app.py"]