"""add_testcase_table_and_update_autoincrement_to_most_primary_key

Revision ID: 116de3a4085d
Revises: bed3c3bbd0b0
Create Date: 2024-11-10 20:32:42.191847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116de3a4085d'
down_revision = 'bed3c3bbd0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase',
    sa.Column('testcaseid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problemid', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.LargeBinary(), nullable=False),
    sa.Column('output_data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['problemid'], ['problem.problemid'], ),
    sa.PrimaryKeyConstraint('testcaseid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testcase')
    # ### end Alembic commands ###
