"""add_limit_to_problem_table_and_set_server_default_to_some_column

Revision ID: 5b1e4acb60d6
Revises: f454a9143bef
Create Date: 2024-11-15 12:26:45.687064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1e4acb60d6'
down_revision = 'f454a9143bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('course', 'is_activate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('course', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('homework', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('problem', sa.Column('memory_limit', sa.Float(), server_default='256.0', nullable=False))
    op.add_column('problem', sa.Column('runtime_limit', sa.Float(), server_default='1.0', nullable=False))
    op.alter_column('problem', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('submission', 'memory',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'memory',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('problem', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('problem', 'runtime')
    op.drop_column('problem', 'memory_limit')
    op.alter_column('homework', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('course', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('course', 'is_activate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('announcement', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
