"""add_courseuser_table

Revision ID: 627f3bcbfddb
Revises: bb54aac9472e
Create Date: 2024-10-30 14:23:54.542707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627f3bcbfddb'
down_revision = 'bb54aac9472e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseuser',
    sa.Column('cu_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['course.courseid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('cu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courseuser')
    # ### end Alembic commands ###
