"""reconstruct_testcase_table

Revision ID: 6a502d45f70f
Revises: c0598132f140
Create Date: 2025-01-15 15:36:38.773853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a502d45f70f'
down_revision = 'c0598132f140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('testcase', sa.Column('content', sa.LargeBinary(), nullable=False))
    op.drop_column('testcase', 'output_data')
    op.drop_column('testcase', 'input_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('input_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('testcase', sa.Column('output_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('testcase', 'content')
    op.drop_column('testcase', 'filename')
    # ### end Alembic commands ###
