"""[Update] update user table

Revision ID: 804481669b6c
Revises: e18c43c4f782
Create Date: 2024-10-24 20:44:04.718129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804481669b6c'
down_revision = 'e18c43c4f782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('message', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('submission_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('accepted_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('rank', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'rank')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'accepted_count')
    op.drop_column('users', 'submission_count')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'message')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
