"""update_course_table

Revision ID: bb54aac9472e
Revises: 804481669b6c
Create Date: 2024-10-29 10:11:08.395613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb54aac9472e'
down_revision = '804481669b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('description', sa.String(), nullable=True))
    op.add_column('course', sa.Column('is_activate', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_activate', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_activate')
    op.drop_column('course', 'end_date')
    op.drop_column('course', 'start_date')
    op.drop_column('course', 'is_public')
    op.drop_column('course', 'is_activate')
    op.drop_column('course', 'description')
    # ### end Alembic commands ###
