"""reformat_problem_table

Revision ID: c0598132f140
Revises: 5b1e4acb60d6
Create Date: 2025-01-09 09:18:30.091341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0598132f140'
down_revision = '5b1e4acb60d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('input_format', sa.String(), nullable=False))
    op.add_column('problem', sa.Column('output_format', sa.String(), nullable=False))
    op.add_column('problem', sa.Column('sample_input_1', sa.String(), nullable=True))
    op.add_column('problem', sa.Column('sample_output_1', sa.String(), nullable=True))
    op.add_column('problem', sa.Column('sample_input_2', sa.String(), nullable=True))
    op.add_column('problem', sa.Column('sample_output_2', sa.String(), nullable=True))
    op.add_column('problem', sa.Column('sample_input_3', sa.String(), nullable=True))
    op.add_column('problem', sa.Column('sample_output_3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'sample_output_3')
    op.drop_column('problem', 'sample_input_3')
    op.drop_column('problem', 'sample_output_2')
    op.drop_column('problem', 'sample_input_2')
    op.drop_column('problem', 'sample_output_1')
    op.drop_column('problem', 'sample_input_1')
    op.drop_column('problem', 'output_format')
    op.drop_column('problem', 'input_format')
    # ### end Alembic commands ###
