"""initial migration

Revision ID: e18c43c4f782
Revises: 
Create Date: 2024-10-22 23:55:41.573080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18c43c4f782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(), nullable=False),
    sa.Column('teacher', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('courseid')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('course')
    # ### end Alembic commands ###
