"""add_userid_column_into_submission_table

Revision ID: f454a9143bef
Revises: 116de3a4085d
Create Date: 2024-11-14 18:27:17.719235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f454a9143bef'
down_revision = '116de3a4085d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('userid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'submission', 'users', ['userid'], ['userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'userid')
    # ### end Alembic commands ###
